remote_theme: wet-boew/gcweb-jekyll
title: Canada.ca design system

language: en

baseurl: ""
url: "http://localhost:4000"  

# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
