url: "https://deploy-preview-253--design-system-canada-ca.netlify.app" # adjust for branch
urlconceptioncanadaca: "https://conception.canada.ca"
urlcanadaca: "https://www.canada.ca"
urlblogca: "https://blog.canada.ca"
