remote_theme: wet-boew/gcweb-jekyll
title: Canada.ca design system

language: en

baseurl: ""
url: "https://design.canada.ca/preview/"

# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
