name: Jekyll PR Preview

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          sudo gem install bundler
          sudo bundle install
          npm install

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: .
          target_path: preview

      - name: Preview URL
        run: echo "Preview URL https://design.canada.ca/${{ github.ref }}/preview/"
